version: '3.1'

services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    ports:
      - "27018:27017"
    volumes:
      - ../../mongo/db:/data/db
      - ../../mongo/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nintendo
      MONGO_INITDB_DATABASE: models
      TZ: Asia/Tokyo